name: update-readme

on:
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.1]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: 🍽️ Get working copy
      uses: actions/checkout@main
      with:
        fetch-depth: 1  
    - name: Install dependencies and run
      run: |
        npm ci
        npm start
    - name: 🚀 Deploy
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "Update dynamic content"
        git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
